server:
  port: 8081

spring:
  datasource:
    name:
    url: jdbc:mysql://{ip}:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: {password}

mybatis:
  mapper-locations: classpath:mapper/*.xml